services:
  app:
    build: .
    container_name: app
    hostname: app
    ports:
      - 8080:8080
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - network

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -server -data-dir=/consul/data -bootstrap=true -ui -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data
    networks:
      - network

volumes:
  consul-data:

networks:
  network:
    driver: bridge